server:
  port: 80

swagger:
  enable: true
spring:
  datasource:
    druid:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动包
        url: jdbc:mysql://47.111.224.180:8306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: root
        password: 12345678
        initial-size: 10
        max-active: 100
        min-idle: 10
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动包
        url: jdbc:mysql://47.111.224.180:8306/test_read?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: root
        password: 12345678
        initial-size: 10
        max-active: 100
        min-idle: 10
